@extends('layouts.app')

@section('content')
<div class="container mt-4 user-detail-page">
    <div class="user-detail-hero"><div class="user-detail-profile"><img src="{{ $user->profile_photo_path ? asset('storage/' . $user->profile_photo_path) : asset('images/default-avatar.svg') }}" alt="Foto profil {{ $user->name }}"><div><div class="user-detail-kicker">PROFIL USER</div><h1>{{ $user->name }}</h1><p>{{ $user->email }}</p></div></div><div class="d-flex flex-wrap gap-2"><a href="{{ route('users.edit', $user) }}" class="btn btn-light">Edit User</a><a href="{{ route('users.index') }}" class="btn btn-outline-light">Kembali</a></div></div>
    <div class="row g-3 my-1"><div class="col-md-4"><div class="user-detail-stat"><span>Hak Akses</span><strong>{{ $user->roleLabel() }}</strong></div></div><div class="col-md-4"><div class="user-detail-stat"><span>Departemen</span><strong>{{ $user->department ?: '-' }}</strong></div></div><div class="col-md-4"><div class="user-detail-stat"><span>Peralatan Dipegang</span><strong>{{ $user->equipments->count() }} unit</strong></div></div></div>
    <section class="card user-equipment-card mt-3"><div class="card-header d-flex justify-content-between align-items-center"><div><div class="user-detail-kicker">ASSET ASSIGNMENT</div><h2>Peralatan IT yang Dipegang</h2></div><span class="badge bg-primary">{{ $user->equipments->count() }} unit</span></div><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Peralatan</th><th>Kode Aset</th><th>Tipe</th><th>Manufacturer</th><th>Lokasi</th><th>Kondisi</th><th></th></tr></thead><tbody>@forelse($user->equipments->sortBy('name') as $equipment)<tr><td><strong>{{ $equipment->name }}</strong><small class="d-block text-muted">{{ $equipment->model ?: 'Model belum dicatat' }}</small></td><td>{{ $equipment->asset_tag ?: '-' }}</td><td>{{ $equipment->type->name ?? '-' }}</td><td>{{ $equipment->manufacturer->name ?? '-' }}</td><td>{{ $equipment->assetLocation->name ?? '-' }}</td><td>{{ ucfirst($equipment->condition ?: $equipment->status ?: '-') }}</td><td class="text-nowrap"><a href="{{ route('equipments.show', $equipment) }}" class="btn btn-sm btn-outline-primary">Detail Aset</a><form method="POST" action="{{ route('users.equipments.detach', [$user, $equipment]) }}" class="d-inline" onsubmit="return confirm('Lepas peralatan {{ $equipment->name }} dari {{ $user->name }}?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Lepas Peralatan</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-5">Belum ada peralatan IT yang ditugaskan kepada user ini.</td></tr>@endforelse</tbody></table></div></div></section>
</div>
<style>.user-detail-page{color:#17324d}.user-detail-hero{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:26px 30px;border-radius:8px;background:linear-gradient(120deg,#075985,#0f766e);color:#fff}.user-detail-profile{display:flex;align-items:center;gap:16px;min-width:0}.user-detail-profile img{width:72px;height:72px;flex:0 0 72px;border:3px solid rgba(255,255,255,.55);border-radius:50%;object-fit:cover;background:#e0f2fe}.user-detail-kicker{font-size:.7rem;font-weight:800;letter-spacing:.11em}.user-detail-hero h1{margin:4px 0;font-size:1.65rem}.user-detail-hero p{margin:0;color:#dbeafe}.user-detail-stat{height:100%;padding:16px 18px;border:1px solid #dbe5ef;border-top:4px solid #0b5ea8;background:#fff}.user-detail-stat span{display:block;color:#64748b;font-size:.76rem}.user-detail-stat strong{display:block;margin-top:4px;font-size:1.1rem}.user-equipment-card{border:1px solid #dbe5ef}.user-equipment-card .card-header{padding:17px 20px;background:#f8fafc}.user-equipment-card h2{margin:4px 0 0;font-size:1.08rem}.user-equipment-card thead th{background:#fff6e4;font-size:.76rem;text-transform:uppercase}@media(max-width:650px){.user-detail-hero{padding:22px;align-items:flex-start;flex-direction:column}.user-detail-profile img{width:58px;height:58px;flex-basis:58px}}</style>
@endsection
