@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><h2 class="mb-1">Limbah IT</h2><p class="text-muted mb-0">Buat box atau batch terlebih dahulu, kemudian catat limbah harian di dalamnya.</p></div><a href="{{ route('it-wastes.create') }}" class="btn btn-primary">Buat Box / Batch Baru</a></div>
    <div class="row g-3 mb-3"><div class="col-md-3"><div class="border border-top border-primary border-3 p-3 bg-white"><span class="text-muted small d-block">Total Catatan</span><strong class="fs-4">{{ $summary['records'] }}</strong></div></div><div class="col-md-3"><div class="border border-top border-warning border-3 p-3 bg-white"><span class="text-muted small d-block">Jenis Limbah</span><strong class="fs-4">{{ $summary['types'] }}</strong></div></div><div class="col-md-3"><div class="border border-top border-success border-3 p-3 bg-white"><span class="text-muted small d-block">Dicatat Bulan Ini</span><strong class="fs-4">{{ $summary['this_month'] }}</strong></div></div><div class="col-md-3"><div class="border border-top border-danger border-3 p-3 bg-white"><span class="text-muted small d-block">Siap Diserahkan</span><strong class="fs-4">{{ $summary['ready_to_handover'] }}</strong></div></div></div>
    @if ($handoverBoxes->isNotEmpty())<form method="GET" action="{{ route('it-wastes.print-handover') }}" target="_blank" class="d-flex flex-wrap align-items-end gap-2 mb-3 p-3 border rounded bg-light"><div><label for="handover_box" class="form-label mb-1">Box yang Sudah Diserahkan</label><select id="handover_box" name="box_code" class="form-select" required>@foreach ($handoverBoxes as $box)<option value="{{ $box }}">{{ $box }}</option>@endforeach</select></div><button class="btn btn-outline-primary"><i class="bi bi-printer"></i> Cetak Serah Terima Limbah</button></form>@endif
    <div class="card"><div class="card-header d-flex flex-wrap justify-content-between align-items-center gap-2"><strong>Daftar Box / Batch Limbah</strong><form method="GET" class="d-flex gap-2"><input name="search" value="{{ $search }}" class="form-control form-control-sm" placeholder="Cari kode box atau lokasi"><button class="btn btn-sm btn-outline-primary">Cari</button></form></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Kode Box</th><th>Tanggal Dibuat</th><th>Lokasi</th><th>Jumlah Limbah</th><th>Status</th><th>Serah Terima B3</th><th>Aksi</th></tr></thead><tbody>@forelse($batches as $batch)<tr><td><strong>{{ $batch->box_code }}</strong></td><td>{{ $batch->opened_at->format('d M Y') }}</td><td>{{ $batch->storage_location ?: '-' }}</td><td>{{ $batch->wastes_count }} catatan</td><td><span class="badge {{ $batch->status === 'handed_over' ? 'bg-success' : ($batch->status === 'ready_to_handover' ? 'bg-warning text-dark' : 'bg-primary') }}">{{ ['open' => 'Box Terbuka', 'ready_to_handover' => 'Siap Diserahkan', 'handed_over' => 'Sudah Diserahkan ke B3'][$batch->status] }}</span></td><td>{{ $batch->handed_over_at?->format('d M Y') ?? '-' }}<small class="d-block text-muted">{{ $batch->handover_recipient ?: '' }}</small></td><td class="text-nowrap"><a href="{{ route('it-wastes.show', $batch) }}" class="btn btn-sm btn-outline-primary">Buka Batch</a>@if ($batch->wastes_count === 0)<form method="POST" action="{{ route('it-wastes.batches.destroy', $batch) }}" class="d-inline" onsubmit="return confirm('Hapus box {{ $batch->box_code }}?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form>@else<span class="d-block small text-muted mt-1">Tidak dapat dihapus karena berisi limbah</span>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada box atau batch limbah.</td></tr>@endforelse</tbody></table></div></div><div class="table-pagination">{{ $batches->links() }}</div>
</div>
@endsection
