@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><h2 class="mb-1">Batch Limbah {{ $itWasteBatch->box_code }}</h2><p class="text-muted mb-0">Dibuat {{ $itWasteBatch->opened_at->format('d M Y') }} · {{ $itWasteBatch->storage_location ?: 'Lokasi belum dicatat' }}</p></div><a href="{{ route('it-wastes.index') }}" class="btn btn-outline-secondary">Kembali</a></div>

    <div class="card mb-3"><div class="card-body"><form method="POST" action="{{ route('it-wastes.batches.update', $itWasteBatch) }}" class="row g-3 align-items-end">@csrf @method('PUT')<div class="col-md-4"><label class="form-label">Status Box</label><select name="status" id="batch_status" class="form-select" {{ $itWasteBatch->status === 'handed_over' ? 'disabled' : '' }}><option value="open" {{ $itWasteBatch->status === 'open' ? 'selected' : '' }}>Box Terbuka</option><option value="ready_to_handover" {{ $itWasteBatch->status === 'ready_to_handover' ? 'selected' : '' }}>Box Penuh / Siap Diserahkan</option><option value="handed_over" {{ $itWasteBatch->status === 'handed_over' ? 'selected' : '' }}>Sudah Diserahkan ke Limbah B3</option></select></div><div class="col-md-4"><label class="form-label">Tanggal Serah Terima</label><input type="date" name="handed_over_at" id="batch_handover_date" class="form-control" value="{{ old('handed_over_at', optional($itWasteBatch->handed_over_at)->format('Y-m-d')) }}" {{ $itWasteBatch->status === 'handed_over' ? 'disabled' : '' }}></div><div class="col-md-4"><label class="form-label">Penerima Limbah B3</label><input name="handover_recipient" id="batch_recipient" class="form-control" value="{{ old('handover_recipient', $itWasteBatch->handover_recipient) }}" {{ $itWasteBatch->status === 'handed_over' ? 'disabled' : '' }}></div>@if ($itWasteBatch->status !== 'handed_over')<div class="col-12"><button class="btn btn-outline-primary">Simpan Status Box</button></div>@else<div class="col-12"><div class="alert alert-success py-2 mb-2">Box ini sudah diserahkan ke Limbah B3. Berita acara serah terima siap dicetak.</div><a href="{{ route('it-wastes.print-handover', ['box_code' => $itWasteBatch->box_code]) }}" target="_blank" class="btn btn-primary"><i class="bi bi-printer"></i> Cetak BA Serah Terima</a></div>@endif</form></div></div>

    @if ($itWasteBatch->status === 'open')
        <div class="card mb-3"><div class="card-header"><strong>Tambahkan Limbah ke Batch</strong><small class="d-block text-muted">Kode limbah dibuat otomatis saat disimpan.</small></div><div class="card-body"><form method="POST" action="{{ route('it-wastes.wastes.store', $itWasteBatch) }}" class="row g-3">@csrf<div class="col-md-4"><label class="form-label">Kode Limbah</label><input class="form-control" value="{{ $nextWasteCode }}" disabled></div><div class="col-md-4"><label class="form-label">Tanggal Limbah</label><input type="date" name="waste_date" class="form-control" value="{{ old('waste_date', now()->format('Y-m-d')) }}" required></div><div class="col-md-4"><label class="form-label">Jenis Limbah</label><select name="waste_type" class="form-select" required><option value="">-- Pilih Jenis --</option>@foreach (['Botol Tinta Bekas', 'Sisa Tinta', 'Limbah Cleaning Printer', 'Cartridge / Toner Bekas', 'Baterai Bekas', 'Kabel Elektronik', 'Komponen Elektronik', 'Lainnya'] as $type)<option value="{{ $type }}">{{ $type }}</option>@endforeach</select></div><div class="col-md-8"><label class="form-label">Deskripsi Limbah</label><input name="description" class="form-control" placeholder="Contoh: Botol tinta HP 682 Black kosong" required></div><div class="col-md-4"><label class="form-label">Jumlah dan Satuan</label><div class="input-group"><input type="number" name="quantity" class="form-control" min="0.01" step="0.01" value="1" required><input name="unit" class="form-control" value="pcs" required></div></div><div class="col-md-6"><label class="form-label">Sumber Peralatan</label><select name="equipment_id" class="form-select"><option value="">Tidak dikaitkan dengan peralatan</option>@foreach ($equipments as $equipment)<option value="{{ $equipment->id }}">{{ $equipment->name }}{{ $equipment->asset_tag ? ' - ' . $equipment->asset_tag : '' }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Metode Penanganan</label><input name="handling_method" class="form-control" placeholder="Contoh: Dikumpulkan untuk vendor B3"></div><div class="col-12"><label class="form-label">Keterangan</label><textarea name="notes" rows="2" class="form-control"></textarea></div><div class="col-12"><button class="btn btn-primary">Tambah Limbah</button></div></form></div></div>
    @else
        <div class="alert alert-secondary">Batch sudah ditutup sehingga tidak dapat ditambahkan limbah baru.</div>
    @endif

    <div class="card"><div class="card-header"><strong>Isi Batch</strong></div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Kode Limbah</th><th>Tanggal</th><th>Jenis</th><th>Deskripsi</th><th>Jumlah</th><th>Peralatan</th><th>Keterangan</th><th></th></tr></thead><tbody>@forelse ($itWasteBatch->wastes->sortByDesc('waste_date') as $waste)<tr><td><strong>{{ $waste->waste_code }}</strong></td><td>{{ $waste->waste_date->format('d M Y') }}</td><td>{{ $waste->waste_type }}</td><td>{{ $waste->description }}</td><td>{{ rtrim(rtrim(number_format($waste->quantity, 2, ',', '.'), '0'), ',') }} {{ $waste->unit }}</td><td>{{ $waste->equipment->name ?? '-' }}</td><td>{{ $waste->notes ?: '-' }}</td><td><a href="{{ route('it-wastes.edit', $waste) }}" class="btn btn-sm btn-outline-primary">Edit</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Belum ada limbah dalam batch ini.</td></tr>@endforelse</tbody></table></div></div>
</div>
<script>
    (() => {
        const status = document.getElementById('batch_status');
        const date = document.getElementById('batch_handover_date');
        const recipient = document.getElementById('batch_recipient');
        if (!status) return;
        const sync = () => { const required = status.value === 'handed_over'; date.required = required; recipient.required = required; };
        status.addEventListener('change', sync); sync();
    })();
</script>
@endsection
