@extends('layouts.app')

@section('content')
<div class="container mt-4 transfer-page">
    <div class="d-flex justify-content-between align-items-start mb-3"><div><div class="text-uppercase fw-bold small text-primary">Peralatan IT</div><h2 class="mb-1">Mutasi Peralatan</h2><p class="text-muted mb-0">Kelola perpindahan PIC, lokasi, dan riwayat serah terima peralatan.</p></div><a href="{{ route('equipment-transfers.create') }}" class="btn btn-brand">Buat Mutasi</a></div>
    <div class="row g-3 mb-3">@foreach(['pending_approval' => ['Menunggu Persetujuan','warning'], 'approved' => ['Siap Serah Terima','primary'], 'completed' => ['Selesai','success'], 'rejected' => ['Ditolak','danger']] as $key => [$label, $color])<div class="col-6 col-lg-3"><div class="transfer-stat border-top border-{{ $color }}"><span>{{ $label }}</span><strong>{{ $summary[$key] }}</strong></div></div>@endforeach</div>
    <div class="card transfer-list"><div class="card-header d-flex justify-content-between align-items-center"><strong>Riwayat Mutasi</strong><form method="GET"><select name="status" class="form-select form-select-sm" onchange="this.form.submit()"><option value="">Semua status</option>@foreach(['pending_approval' => 'Menunggu Persetujuan','approved' => 'Disetujui','completed' => 'Selesai','rejected' => 'Ditolak'] as $key => $label)<option value="{{ $key }}" @selected($status === $key)>{{ $label }}</option>@endforeach</select></form></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Peralatan</th><th>Dari</th><th>Ke</th><th>Tanggal Efektif</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($transfers as $transfer)<tr><td><strong>{{ $transfer->equipment->name }}</strong><small class="d-block text-muted">{{ $transfer->equipment->asset_tag ?: '-' }}</small></td><td>{{ $transfer->from_owner_name ?: '-' }}</td><td>{{ $transfer->to_owner_name ?: '-' }}</td><td>{{ $transfer->effective_date?->format('d M Y') }}</td><td><span class="transfer-badge transfer-{{ $transfer->status }}">{{ ['pending_approval'=>'Menunggu Persetujuan','approved'=>'Disetujui','completed'=>'Selesai','rejected'=>'Ditolak'][$transfer->status] ?? $transfer->status }}</span></td><td><a href="{{ route('equipment-transfers.show', $transfer) }}" class="btn btn-sm btn-outline-primary">Detail</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada riwayat mutasi.</td></tr>@endforelse</tbody></table></div><div class="table-pagination">{{ $transfers->links() }}</div></div>
</div>
<style>.transfer-stat{padding:15px 17px;background:#fff;border:1px solid #dbe5ef;border-top-width:4px!important}.transfer-stat span{display:block;color:#64748b;font-size:.78rem}.transfer-stat strong{display:block;font-size:1.6rem}.transfer-list{border:1px solid #dbe5ef}.transfer-list .card-header{background:#f8fafc}.transfer-list .card-header form{width:220px}.transfer-badge{display:inline-block;padding:4px 7px;border-radius:3px;font-size:.72rem;font-weight:700}.transfer-pending_approval{background:#fef3c7;color:#92400e}.transfer-approved{background:#dbeafe;color:#1d4ed8}.transfer-completed{background:#dcfce7;color:#166534}.transfer-rejected{background:#fee2e2;color:#991b1b}@media(max-width:575px){.transfer-list .card-header{align-items:flex-start!important;gap:10px;flex-direction:column}.transfer-list .card-header form{width:100%}}</style>
@endsection
