@extends('layouts.app')

@section('content')
<div class="container mt-4 transfer-page">
    <div class="d-flex justify-content-between align-items-start mb-3"><div class="d-flex align-items-start gap-3"><span class="workflow-page-icon transfer-icon"><i class="bi bi-arrow-left-right"></i></span><div><div class="workflow-eyebrow">Asset Movement</div><h2 class="mb-1">Mutasi Peralatan</h2><p class="text-muted mb-0">Kelola perpindahan PIC, lokasi, dan riwayat serah terima peralatan.</p></div></div><a href="{{ route('equipment-transfers.create') }}" class="btn btn-brand"><i class="bi bi-plus-lg"></i>Buat Mutasi</a></div>
    <div class="row g-3 mb-3">@foreach(['pending_approval' => ['Menunggu Persetujuan','warning'], 'approved' => ['Siap Serah Terima','primary'], 'completed' => ['Selesai','success'], 'rejected' => ['Ditolak','danger']] as $key => [$label, $color])<div class="col-6 col-lg-3"><div class="transfer-stat border-top border-{{ $color }}"><span>{{ $label }}</span><strong>{{ $summary[$key] }}</strong></div></div>@endforeach</div>
    <div class="card transfer-list"><div class="card-header d-flex justify-content-between align-items-center"><strong>Riwayat Mutasi</strong><form method="GET"><select name="status" class="form-select form-select-sm" onchange="this.form.submit()"><option value="">Semua status</option>@foreach(['pending_approval' => 'Menunggu Persetujuan','approved' => 'Disetujui','completed' => 'Selesai','rejected' => 'Ditolak'] as $key => $label)<option value="{{ $key }}" @selected($status === $key)>{{ $label }}</option>@endforeach</select></form></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Peralatan</th><th>Dari</th><th>Ke</th><th>Tanggal Efektif</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($transfers as $transfer)<tr><td><strong>{{ $transfer->equipment->name }}</strong><small class="d-block text-muted">{{ $transfer->equipment->asset_tag ?: '-' }}</small></td><td>{{ $transfer->from_owner_name ?: '-' }}</td><td>{{ $transfer->to_owner_name ?: '-' }}</td><td>{{ $transfer->effective_date?->format('d M Y') }}</td><td><span class="transfer-badge transfer-{{ $transfer->status }}">{{ ['pending_approval'=>'Menunggu Persetujuan','approved'=>'Disetujui','completed'=>'Selesai','rejected'=>'Ditolak'][$transfer->status] ?? $transfer->status }}</span></td><td><a href="{{ route('equipment-transfers.show', $transfer) }}" class="btn btn-sm btn-outline-primary">Detail</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada riwayat mutasi.</td></tr>@endforelse</tbody></table></div><div class="table-pagination">{{ $transfers->links() }}</div></div>
</div>
<style>.transfer-stat{padding:15px 17px;background:#fff;border:1px solid #dbe5ef;border-top-width:4px!important}.transfer-stat span{display:block;color:#64748b;font-size:.78rem}.transfer-stat strong{display:block;font-size:1.6rem}.transfer-list{border:1px solid #dbe5ef}.transfer-list .card-header{background:#f8fafc}.transfer-list .card-header form{width:220px}.transfer-badge{display:inline-block;padding:4px 7px;border-radius:3px;font-size:.72rem;font-weight:700}.transfer-pending_approval{background:#fef3c7;color:#92400e}.transfer-approved{background:#dbeafe;color:#1d4ed8}.transfer-completed{background:#dcfce7;color:#166534}.transfer-rejected{background:#fee2e2;color:#991b1b}@media(max-width:575px){.transfer-list .card-header{align-items:flex-start!important;gap:10px;flex-direction:column}.transfer-list .card-header form{width:100%}}</style>
<style>
.transfer-page{max-width:1480px;margin-top:0!important;color:#18243d}.transfer-page>div:first-child{padding:4px 4px 18px;border-bottom:1px solid #e8edf4}.workflow-page-icon{display:flex;align-items:center;justify-content:center;width:46px;height:46px;flex:0 0 46px;border-radius:14px;background:linear-gradient(135deg,#7c5cfc,#a78bfa);color:#fff;font-size:1.15rem;box-shadow:0 8px 16px rgba(124,92,252,.25)}.workflow-eyebrow{color:#7c5cfc;font-size:.68rem;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.transfer-page h2{color:#18243d;font-size:1.8rem;font-weight:800;letter-spacing:-.03em}.transfer-page .text-muted{color:#8792a7!important;font-size:.78rem}.transfer-page .btn-brand{border-radius:10px;padding:10px 16px;background:linear-gradient(135deg,#7c5cfc,#a78bfa);box-shadow:0 8px 16px rgba(124,92,252,.2);font-weight:700}.transfer-page .btn-brand i{margin-right:7px}
.transfer-page .transfer-stat{position:relative;min-height:116px;padding:19px 20px;border:1px solid #ece9fb!important;border-top:0!important;border-radius:16px;background:#fff;box-shadow:0 7px 20px rgba(92,71,207,.06);overflow:hidden}.transfer-page .transfer-stat:after{content:'';position:absolute;right:-22px;bottom:-34px;width:90px;height:90px;border-radius:50%;background:currentColor;opacity:.06}.transfer-page .transfer-stat span{color:#78849a;font-size:.72rem;font-weight:700}.transfer-page .transfer-stat strong{display:block;margin-top:9px;color:#18243d;font-size:1.85rem;font-weight:800}.transfer-page .transfer-stat.border-warning{color:#f3b54b}.transfer-page .transfer-stat.border-primary{color:#7c5cfc}.transfer-page .transfer-stat.border-success{color:#14b8a6}.transfer-page .transfer-stat.border-danger{color:#f43f5e}
.transfer-page .transfer-list{border-radius:16px;border-color:#e7ebf2;overflow:hidden}.transfer-page .card-header{padding:17px 20px;background:#fff}.transfer-page .card-header strong{font-size:.9rem}.transfer-page .card-header form{width:220px}.transfer-page .card-header select{border-radius:9px;border-color:#dfe5ee;color:#536079;font-size:.74rem}.transfer-page .table{font-size:.77rem}.transfer-page .table thead th{padding:13px 16px;background:#f8f7ff;color:#7d899e;font-size:.65rem;font-weight:800;letter-spacing:.04em;text-transform:uppercase;white-space:nowrap}.transfer-page .table tbody td{padding:15px 16px;border-color:#eef1f5;color:#536079}.transfer-page .table tbody tr:hover{background:#faf9ff}.transfer-page .table td strong{color:#26324b}.transfer-page .table small{font-size:.67rem}.transfer-page .transfer-badge{padding:6px 10px;border-radius:999px;font-size:.67rem}.transfer-page .transfer-pending_approval{background:#fff5dc;color:#b77908}.transfer-page .transfer-approved{background:#efeafe;color:#6b46d9}.transfer-page .transfer-completed{background:#e2f8f4;color:#0f9c8a}.transfer-page .transfer-rejected{background:#ffeef0;color:#e11d48}.transfer-page .btn-sm{border-radius:8px;font-weight:700;font-size:.7rem}.transfer-page .table-pagination{padding:14px 20px;background:#fff}.transfer-page .page-link{border-radius:8px;margin-left:4px!important}
@media(max-width:575px){.transfer-page>div:first-child{gap:14px;flex-direction:column!important}.transfer-page>div:first-child>.btn{align-self:stretch}.transfer-list .card-header{align-items:flex-start!important;gap:10px;flex-direction:column}.transfer-list .card-header form{width:100%}}
</style>
@endsection
