@extends('layouts.app')

@section('content')
<div class="container mt-4 transfer-page">
    <div class="d-flex justify-content-between align-items-start mb-3"><div><div class="text-uppercase fw-bold small text-primary">Mutasi Peralatan</div><h2 class="mb-1">Detail Mutasi</h2><p class="text-muted mb-0">{{ $transfer->equipment->name }} - {{ $transfer->equipment->asset_tag ?: 'Tanpa kode aset' }}</p></div><div class="d-flex gap-2 flex-wrap justify-content-end"><a href="{{ route('equipment-transfers.print', $transfer) }}" class="btn btn-primary" target="_blank" rel="noopener">Cetak Mutasi</a><a href="{{ route('equipment-transfers.index') }}" class="btn btn-outline-secondary">Kembali</a>@if(auth()->user()->isMaster())<form method="POST" action="{{ route('equipment-transfers.destroy', $transfer) }}" onsubmit="return confirm('Hapus riwayat mutasi ini?')">@csrf @method('DELETE')<button type="submit" class="btn btn-outline-danger">Hapus</button></form>@endif</div></div>
    <div class="card transfer-detail"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-4"><h3 class="h5 mb-0">{{ $statuses[$transfer->status] }}</h3><span class="transfer-badge transfer-{{ $transfer->status }}">{{ $statuses[$transfer->status] }}</span></div><div class="row g-4"><div class="col-md-6"><h4 class="h6 text-muted">Pemegang Sebelumnya</h4><dl><dt>PIC</dt><dd>{{ $transfer->from_owner_name ?: '-' }}</dd><dt>Departemen</dt><dd>{{ $transfer->from_department ?: '-' }}</dd><dt>Lokasi</dt><dd>{{ $transfer->fromLocation->name ?? '-' }}</dd></dl></div><div class="col-md-6"><h4 class="h6 text-muted">Pemegang Baru</h4><dl><dt>PIC</dt><dd>{{ $transfer->to_owner_name ?: '-' }}</dd><dt>Departemen</dt><dd>{{ $transfer->to_department ?: '-' }}</dd><dt>Lokasi</dt><dd>{{ $transfer->toLocation->name ?? 'Tidak diubah' }}</dd></dl></div></div><hr><dl class="row"><dt class="col-sm-3">Tanggal Efektif</dt><dd class="col-sm-9">{{ $transfer->effective_date?->format('d M Y') }}</dd><dt class="col-sm-3">Alasan</dt><dd class="col-sm-9">{!! nl2br(e($transfer->reason)) !!}</dd><dt class="col-sm-3">Pengaju</dt><dd class="col-sm-9">{{ $transfer->requester->name ?? '-' }}</dd>@if($transfer->notes)<dt class="col-sm-3">Catatan</dt><dd class="col-sm-9">{!! nl2br(e($transfer->notes)) !!}</dd>@endif</dl><div class="d-flex gap-2 flex-wrap">@if($transfer->status === 'pending_approval' && auth()->user()->isMaster())<form method="POST" action="{{ route('equipment-transfers.approve', $transfer) }}">@csrf<input type="hidden" name="action" value="approve"><button class="btn btn-brand">Setujui Mutasi</button></form><form method="POST" action="{{ route('equipment-transfers.approve', $transfer) }}">@csrf<input type="hidden" name="action" value="reject"><button class="btn btn-outline-danger">Tolak</button></form>@endif @if($transfer->status === 'approved')<form method="POST" action="{{ route('equipment-transfers.complete', $transfer) }}">@csrf<button class="btn btn-brand">Selesaikan Serah Terima</button></form>@endif</div></div></div>
</div>
<style>.transfer-detail{border:1px solid #dbe5ef}.transfer-detail dt{color:#64748b;font-size:.76rem;text-transform:uppercase;letter-spacing:.04em}.transfer-detail dd{margin-bottom:12px}.transfer-badge{display:inline-block;padding:4px 7px;border-radius:3px;font-size:.72rem;font-weight:700}.transfer-pending_approval{background:#fef3c7;color:#92400e}.transfer-approved{background:#dbeafe;color:#1d4ed8}.transfer-completed{background:#dcfce7;color:#166534}.transfer-rejected{background:#fee2e2;color:#991b1b}</style>
@endsection
