<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <title>Print Semua Checklist</title>
    <style>
        @page{size:A4 portrait;margin:9mm}*{box-sizing:border-box}body{margin:0;background:#e5e7eb;font-family:'Segoe UI',Arial,Helvetica,sans-serif;color:#17324d;font-size:11px}.sheet{width:192mm;margin:8mm auto;background:#fff;border:1px solid #cbd5e1;border-radius:6px;overflow:hidden;page-break-after:always}.sheet:last-child{page-break-after:auto}.sheet-head{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:12px 16px;background:linear-gradient(120deg,#0b5ea8,#1f8fe0);color:#fff}.sheet-brand{display:flex;align-items:center;gap:11px}.sheet-logo{width:44px;height:44px;object-fit:contain;background:#fff;border-radius:8px;padding:2px}.sheet-brand strong{display:block;font-size:14px;letter-spacing:.04em}.sheet-brand small{display:block;font-size:10px;opacity:.9}.sheet-form-no{display:block;width:fit-content;margin-top:3px;padding:1px 7px;border-radius:9px;background:rgba(255,255,255,.22);font-size:9px;font-weight:700}.sheet-id{text-align:right}.sheet-number{display:block;font-size:16px;font-weight:800}.sheet-chips{display:flex;gap:5px;justify-content:flex-end;margin-top:4px}.chip{padding:3px 8px;border-radius:11px;font-size:9.5px;font-weight:700;background:#fff;color:#0b5ea8}.chip-approved{background:#dcfce7;color:#166534}.sheet-strip{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:#dbe5ef;border-bottom:1px solid #dbe5ef}.sheet-strip div{padding:7px 10px;background:#f8fafc}.sheet-strip span{display:block;font-size:8.5px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:#64748b}.sheet-strip strong{display:block;margin-top:2px;font-size:10.5px}.sheet-table{width:100%;border-collapse:collapse;margin:0}.sheet-table th,.sheet-table td{border:1px solid #dbe5ef;padding:6px 8px;font-size:10.5px}.sheet-table th{background:#fff3e6;text-align:left}.sheet-table td small{display:block;color:#64748b;font-size:9px}.note{margin:10px 16px;padding:8px 10px;background:#f8fafc;border-left:3px solid #0b5ea8;border-radius:0 4px 4px 0}.note span{display:block;font-size:8.5px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:#64748b}.note p{margin:3px 0 0;white-space:pre-line;font-size:10.5px}.sheet-sign{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;padding:14px 16px 10px;border-top:1px solid #dbe5ef;background:#fbfdff;position:relative}.sheet-sign span{display:block;font-size:9px;font-weight:700;text-transform:uppercase;color:#64748b}.sheet-sign i{display:flex;align-items:flex-end;justify-content:center;height:44px}.sheet-sign i img{max-height:44px;max-width:150px;object-fit:contain}.sheet-sign strong{display:block;padding-top:3px;border-top:1px solid #94a3b8;font-size:10.5px}.sheet-sign em{display:block;font-style:normal;font-size:9px;color:#64748b}.sheet-print-time{grid-column:1 / -1;font-size:8.5px;color:#94a3b8;text-align:right}@media print{body{background:#fff}.sheet{width:auto;margin:0;border-radius:0}.print-actions{display:none!important}}
    </style>
</head>
<body>
    <div class="print-actions" style="position:fixed;z-index:5;top:12px;right:12px"><button type="button" onclick="window.print()">Print</button><button type="button" onclick="window.close()">Kembali</button></div>
    @foreach($documents as $document)
        @php($checklist = $document['checklist'])
        @php($program = $checklist->checklistItem)
        <div class="sheet">
            <header class="sheet-head"><div class="sheet-brand"><img class="sheet-logo" src="{{ asset('images/logo-mgm.svg') }}" alt="Logo"><div><strong>PT MULIA GRAND MANUFACTURE</strong><small>Checklist Perawatan IT</small><span class="sheet-form-no">No. Form : FR-IT-03</span><span class="sheet-form-no">Revisi : 00</span></div></div><div class="sheet-id"><span class="sheet-number">{{ $program->title }}</span><div class="sheet-chips"><span class="chip">{{ $document['monthName'] }} {{ $checklist->year }}</span>@if($checklist->acknowledged_at)<span class="chip chip-approved">Approved</span>@endif</div></div></header>
            <section class="sheet-strip"><div><span>Program Perawatan</span><strong>{{ $program->title }}</strong></div><div><span>Periode</span><strong>{{ $document['monthName'] }} {{ $checklist->year }}</strong></div><div><span>Tanggal Input Checklist</span><strong>{{ $checklist->checked_at?->format('d M Y') ?: '-' }}</strong></div><div><span>Total Peralatan</span><strong>{{ $document['summary']['total'] }}</strong></div><div><span>Hasil</span><strong>OK {{ $document['summary']['ok'] }} / NOT OK {{ $document['summary']['not_ok'] }}</strong></div></section>
            <table class="sheet-table"><thead><tr><th>No.</th><th>Nama Peralatan</th><th>Tanggal Jadwal</th><th>Check Point</th><th>Kondisi</th><th>Keterangan</th></tr></thead><tbody>@foreach($checklist->entries->sortBy(fn ($entry) => $entry->equipment?->name) as $index => $entry)<tr><td>{{ $index + 1 }}</td><td>{{ $entry->equipment?->name ?: '-' }}<small>{{ $entry->equipment?->asset_tag ?: ($entry->equipment?->serial_number ?: '-') }}</small></td><td>{{ count($document['scheduledDates']->get($entry->equipment_id, [])) ? implode(', ', $document['scheduledDates']->get($entry->equipment_id)) : '-' }}</td><td>{{ $program->title }}</td><td>{{ $entry->result === 'ok' ? 'OK' : 'NOT OK' }}</td><td>{{ $entry->remarks ?: '-' }}</td></tr>@endforeach</tbody></table>
            @if($checklist->notes)<div class="note"><span>Catatan Dokumen</span><p>{{ $checklist->notes }}</p></div>@endif
            <footer class="sheet-sign"><div><span>Dibuat Oleh</span><i>@if($checklist->reporter?->signature_path)<img src="{{ asset('storage/' . $checklist->reporter->signature_path) }}" alt="Tanda tangan">@endif</i><strong>{{ $checklist->reported_by ?: '-' }}</strong><em>{{ $checklist->reporter?->signature_title ?: 'Admin IT / Bagus' }}</em></div><div><span>Mengetahui</span><i>@if($checklist->acknowledger?->signature_path)<img src="{{ asset('storage/' . $checklist->acknowledger->signature_path) }}" alt="Tanda tangan">@endif</i><strong>{{ $checklist->acknowledged_at ? ($checklist->acknowledged_by ?: '-') : '(...........................)' }}</strong><em>{{ $checklist->acknowledged_at ? ($checklist->acknowledger?->signature_title ?: 'Arifin') : 'Menunggu persetujuan' }}</em></div><div class="sheet-print-time">No. Form : FR-IT-03 &nbsp;|&nbsp; Revisi : 00 &nbsp;|&nbsp; Dicetak: {{ now()->translatedFormat('d F Y H:i') }} WIB</div></footer>
        </div>
    @endforeach
    <script>window.addEventListener('load', () => setTimeout(() => window.print(), 400));</script>
</body>
</html>
