@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="mb-1">Edit Checklist Perawatan</h2><p class="text-muted mb-0">Perbarui kondisi dan keterangan peralatan.</p></div><a href="{{ route('maintenance-checklists.show', $maintenanceChecklist) }}" class="btn btn-outline-secondary">Kembali</a></div>
    <form method="POST" action="{{ route('maintenance-checklists.update', $maintenanceChecklist) }}">@csrf @method('PUT')
        <div class="card checklist-document">
            <div class="card-header"><strong>CHECKLIST PERAWATAN IT</strong><span>{{ $maintenanceChecklist->checklistItem->title }}</span></div>
            <div class="card-body">
                <div class="row g-3 mb-3"><div class="col-md-4"><label class="form-label">Program Perawatan</label><select name="checklist_item_id" class="form-select">@foreach ($items as $item)<option value="{{ $item->id }}" {{ $maintenanceChecklist->checklist_item_id === $item->id ? 'selected' : '' }}>{{ $item->title }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Tahun</label><input type="number" name="year" class="form-control" value="{{ $maintenanceChecklist->year }}" min="2000" max="2100"></div><div class="col-md-3"><label class="form-label">Bulan</label><select name="month" class="form-select">@foreach ($monthNames as $number => $name)<option value="{{ $number }}" {{ $maintenanceChecklist->month === $number ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Tanggal</label><input type="date" name="checked_at" class="form-control" value="{{ old('checked_at', $maintenanceChecklist->checked_at?->format('Y-m-d')) }}"></div><div class="col-md-6"><label class="form-label">Dilaporkan Oleh</label><input name="reported_by" class="form-control" value="{{ old('reported_by', $maintenanceChecklist->reported_by) }}"></div><div class="col-md-6"><label class="form-label">Mengetahui</label><input name="acknowledged_by" class="form-control" value="{{ old('acknowledged_by', $maintenanceChecklist->acknowledged_by) }}"></div></div>
                <div class="table-responsive"><table class="table table-bordered checklist-table"><thead><tr><th>No.</th><th>Nama Peralatan</th><th>Check Point</th><th class="text-center">OK</th><th class="text-center">Not OK</th><th>Keterangan</th></tr></thead><tbody>@foreach ($equipment as $index => $item)@php $entry = $entryIndex->get($item->id); @endphp<tr><td>{{ $index + 1 }}</td><td><strong>{{ $item->name }}</strong><small>{{ $item->asset_tag ?? $item->serial_number }}</small><input type="hidden" name="entries[{{ $index }}][equipment_id]" value="{{ $item->id }}"></td><td>{{ $maintenanceChecklist->checklistItem->title }}</td><td class="text-center"><input type="radio" name="entries[{{ $index }}][result]" value="ok" {{ old('entries.' . $index . '.result', $entry->result) === 'ok' ? 'checked' : '' }}></td><td class="text-center"><input type="radio" name="entries[{{ $index }}][result]" value="not_ok" {{ old('entries.' . $index . '.result', $entry->result) === 'not_ok' ? 'checked' : '' }}></td><td><input name="entries[{{ $index }}][remarks]" class="form-control form-control-sm" value="{{ old('entries.' . $index . '.remarks', $entry->remarks) }}" placeholder="Informasi atau perbaikan"></td></tr>@endforeach</tbody></table></div>
                <div class="mt-3"><label class="form-label">Catatan Dokumen</label><textarea name="notes" class="form-control" rows="2">{{ old('notes', $maintenanceChecklist->notes) }}</textarea></div>
            </div>
            <div class="card-footer text-end"><button class="btn btn-brand">Simpan Perubahan</button></div>
        </div>
    </form>
</div>
<style>.checklist-document .card-header { display:flex; justify-content:space-between; align-items:center; background:#f1f5f9; color:#1e293b; }.checklist-table small { display:block; color:#64748b; font-weight:400; }.checklist-table th { background:#fff3e6; font-size:.82rem; }.checklist-table td { vertical-align:middle; }</style>
@endsection
