@extends('layouts.app')

@section('content')
@php $monthName = $monthNames[$maintenanceChecklist->month]; $program = $maintenanceChecklist->checklistItem; @endphp
<div class="container mt-4 checklist-detail" style="--program-color:{{ $program->schedule_color }};--program-tint:{{ $program->schedule_tint }}">
    <div class="checklist-hero">
        <div><div class="checklist-eyebrow">Dokumen Pelaksanaan Perawatan</div><h1>Checklist Perawatan IT</h1><p>{{ $program->title }} | {{ $monthName }} {{ $maintenanceChecklist->year }}</p></div>
        <div class="checklist-hero-actions"><a href="{{ route('maintenance-checklists.edit', $maintenanceChecklist) }}" class="btn btn-light">Edit</a><a href="{{ route('maintenance-checklists.index') }}" class="btn btn-outline-light">Kembali</a></div>
    </div>

    <div class="row g-3 my-1"><div class="col-md-4"><div class="checklist-stat"><span>Total Peralatan</span><strong>{{ $summary['total'] }}</strong></div></div><div class="col-md-4"><div class="checklist-stat checklist-stat-ok"><span>Kondisi OK</span><strong>{{ $summary['ok'] }}</strong></div></div><div class="col-md-4"><div class="checklist-stat checklist-stat-not-ok"><span>Perlu Tindak Lanjut</span><strong>{{ $summary['not_ok'] }}</strong></div></div></div>

    <div class="card checklist-document mt-3">
        <div class="card-body">
            <div class="document-meta"><div><span>Program Perawatan</span><strong>{{ $program->title }}</strong></div><div><span>Periode</span><strong>{{ $monthName }} {{ $maintenanceChecklist->year }}</strong></div><div><span>Tanggal Pelaksanaan</span><strong>{{ $maintenanceChecklist->checked_at?->format('d M Y') }}</strong></div><div><span>Dilaporkan Oleh</span><strong>{{ $maintenanceChecklist->reported_by ?? '-' }}</strong></div><div><span>Mengetahui</span><strong>{{ $maintenanceChecklist->acknowledged_by ?? '-' }}</strong></div></div>
            <div class="table-responsive"><table class="table table-bordered checklist-table"><thead><tr><th>No.</th><th>Nama Peralatan</th><th>Check Point</th><th class="text-center">Kondisi</th><th>Keterangan</th></tr></thead><tbody>@foreach ($maintenanceChecklist->entries->sortBy(fn ($entry) => $entry->equipment->name) as $index => $entry)<tr><td>{{ $index + 1 }}</td><td><strong>{{ $entry->equipment->name }}</strong><small>{{ $entry->equipment->asset_tag ?? $entry->equipment->serial_number }}</small></td><td>{{ $program->title }}</td><td class="text-center"><span class="result-badge result-{{ $entry->result }}">{{ $entry->result === 'ok' ? 'OK' : 'NOT OK' }}</span></td><td>{{ $entry->remarks ?? '-' }}</td></tr>@endforeach</tbody></table></div>
            @if ($maintenanceChecklist->notes)<div class="document-notes"><span>Catatan Dokumen</span><p>{{ $maintenanceChecklist->notes }}</p></div>@endif
        </div>
    </div>
</div>
<style>.checklist-hero { display:flex; justify-content:space-between; align-items:flex-start; gap:20px; padding:24px; border-radius:8px; background:linear-gradient(120deg,var(--program-color),#0f766e); color:#fff; }.checklist-eyebrow { font-size:.72rem; text-transform:uppercase; letter-spacing:.08em; font-weight:700; opacity:.8; }.checklist-hero h1 { margin:4px 0; font-size:1.55rem; }.checklist-hero p { margin:0; opacity:.92; }.checklist-hero-actions { display:flex; gap:8px; }.checklist-stat { padding:14px 16px; background:#fff; border:1px solid #dbe3ea; border-top:4px solid var(--program-color); }.checklist-stat span { display:block; color:#64748b; font-size:.78rem; }.checklist-stat strong { font-size:1.6rem; }.checklist-stat-ok { border-top-color:#15803d; }.checklist-stat-not-ok { border-top-color:#dc2626; }.checklist-document { border:1px solid #dbe3ea; }.document-meta { display:grid; grid-template-columns:repeat(5,minmax(0,1fr)); gap:12px; padding-bottom:18px; }.document-meta div { min-width:0; }.document-meta span,.document-notes span { display:block; color:#64748b; font-size:.72rem; text-transform:uppercase; letter-spacing:.04em; font-weight:700; }.document-meta strong { display:block; margin-top:4px; font-size:.88rem; overflow-wrap:anywhere; }.checklist-table th { background:var(--program-tint); color:#334155; font-size:.8rem; }.checklist-table td { vertical-align:middle; }.checklist-table small { display:block; color:#64748b; font-weight:400; }.result-badge { display:inline-block; padding:4px 8px; border-radius:3px; font-size:.75rem; font-weight:700; }.result-ok { background:#dcfce7; color:#166534; }.result-not_ok { background:#fee2e2; color:#991b1b; }.document-notes { margin-top:18px; padding:12px; background:#f8fafc; border-left:3px solid var(--program-color); }.document-notes p { margin:5px 0 0; white-space:pre-line; }@media (max-width:767px) { .checklist-hero { flex-direction:column; }.document-meta { grid-template-columns:1fr 1fr; }.checklist-hero-actions { width:100%; }.checklist-hero-actions .btn { flex:1; } }</style>
@endsection
