@extends('layouts.app')

@section('content')
<div class="container-fluid mt-4 target-monitoring-page">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><div class="target-kicker">IT PERFORMANCE CONTROL</div><h2 class="mb-1">Pemantauan Sasaran</h2><p class="text-muted mb-0">Rekap capaian sasaran IT berdasarkan perbaikan, inovasi, dan temuan operasional.</p></div></div>
    <form method="GET" class="row g-3 align-items-end p-3 mb-3 border rounded bg-light"><div class="col-md-3"><label class="form-label">Tahun</label><input type="number" name="year" class="form-control" value="{{ $year }}" min="2000" max="2100"></div><div class="col-md-3"><label class="form-label">Bulan Awal</label><select name="start_month" class="form-select">@foreach($monthOptions as $number => $name)<option value="{{ $number }}" {{ $startMonth === $number ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Bulan Akhir</label><select name="end_month" class="form-select">@foreach($monthOptions as $number => $name)<option value="{{ $number }}" {{ $endMonth === $number ? 'selected' : '' }}>{{ $name }}</option>@endforeach</select></div><div class="col-md-3"><button class="btn btn-primary">Tampilkan Pemantauan</button></div></form>
    <form method="POST" action="{{ route('target-monitorings.manual.update') }}">@csrf<input type="hidden" name="year" value="{{ $year }}"><input type="hidden" name="start_month" value="{{ $startMonth }}"><input type="hidden" name="end_month" value="{{ $endMonth }}"><section class="target-sheet"><header><img src="{{ asset('images/logo-mgm.svg') }}" alt="Logo MGM"><div><strong>PT. MULIA GRAND MANUFACTURE</strong><h3>PEMANTAUAN SASARAN</h3></div><span>Periode: {{ $months->first() }} - {{ $months->last() }} {{ $year }}</span></header><div class="table-responsive"><table class="table table-bordered target-table mb-0"><thead><tr><th rowspan="2">No.</th><th rowspan="2">Sasaran</th><th rowspan="2">Target</th><th colspan="{{ $months->count() }}">Pencapaian Bulan</th><th rowspan="2">Keterangan</th></tr><tr>@foreach($months as $name)<th>{{ $name }}</th>@endforeach</tr></thead><tbody>@foreach($metrics as $index => $metric)<tr><td>{{ $index + 1 }}</td><td class="target-name">{{ $metric['label'] }}</td><td>{{ $metric['target'] }}</td>@foreach($months as $monthNumber => $name)@php($value = $metric['manual'] ? ($manualValues->get($metric['key'] . '|' . $monthNumber)?->value ?? 0) : ($metric['values']->get($monthNumber, 0)))<td class="text-center">@if($metric['manual'])<input type="number" min="0" name="manual[{{ $metric['key'] }}][{{ $monthNumber }}][value]" value="{{ $value }}" class="form-control form-control-sm target-input">@else<span class="target-value">{{ $value }}</span>@endif</td>@endforeach<td><span class="target-result {{ collect($months->keys())->every(fn ($month) => $metric['achieved']($metric['manual'] ? ($manualValues->get($metric['key'] . '|' . $month)?->value ?? 0) : $metric['values']->get($month, 0))) ? 'target-result-ok' : 'target-result-alert' }}">{{ collect($months->keys())->every(fn ($month) => $metric['achieved']($metric['manual'] ? ($manualValues->get($metric['key'] . '|' . $month)?->value ?? 0) : $metric['values']->get($month, 0))) ? 'Tercapai' : 'Perlu Tindak Lanjut' }}</span></td></tr>@endforeach</tbody></table></div><div class="target-actions"><span>Baris 1 dan 2 dihitung otomatis. Baris 3 dan 4 dapat diisi manual.</span><button class="btn btn-primary">Simpan Data Manual</button></div></section></form>
</div>
<style>.target-monitoring-page{color:#17324d}.target-kicker{font-size:.72rem;font-weight:800;color:#0b5ea8;letter-spacing:.11em}.target-sheet{border:1px solid #94a3b8;background:#fff}.target-sheet header{display:grid;grid-template-columns:88px 1fr auto;align-items:center;gap:14px;padding:10px 16px;border-bottom:2px solid #17324d;text-align:center}.target-sheet header img{width:62px;height:62px;object-fit:contain}.target-sheet header strong{display:block;font-size:1rem}.target-sheet header h3{margin:4px 0 0;font-size:1.25rem}.target-sheet header span{font-size:.8rem;font-weight:700}.target-table th,.target-table td{border-color:#334155;vertical-align:middle;font-size:.82rem}.target-table thead th{text-align:center;background:#f8fafc}.target-name{min-width:290px}.target-input{min-width:58px;text-align:center}.target-value{font-size:1rem;font-weight:700}.target-result{display:inline-block;padding:4px 7px;border-radius:3px;font-size:.74rem;font-weight:700}.target-result-ok{background:#dcfce7;color:#166534}.target-result-alert{background:#fee2e2;color:#991b1b}.target-actions{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 16px;background:#f8fafc;font-size:.8rem;color:#64748b}@media(max-width:700px){.target-sheet header{grid-template-columns:54px 1fr}.target-sheet header img{width:46px;height:46px}.target-sheet header span{grid-column:1/-1}.target-actions{align-items:flex-start;flex-direction:column}}</style>
@endsection
