@extends('layouts.app')

@section('content')
<div class="container mt-4 sparepart-page">
    <div class="sparepart-hero mb-4"><div><div class="sparepart-eyebrow">INVENTARIS &amp; PERSEDIAAN</div><h1>Kelola Sparepart</h1><p>Kontrol stok komponen IT, pencatatan pemakaian, dan riwayat pergerakan sparepart.</p></div><div class="sparepart-hero-mark">SP<br><span>PART CONTROL</span></div></div>
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0 ps-3">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row g-3 mb-4"><div class="col-6 col-lg-3"><div class="sparepart-stat stat-blue"><span>Jenis Sparepart</span><strong>{{ $summary['types'] }}</strong><small>master terdaftar</small></div></div><div class="col-6 col-lg-3"><div class="sparepart-stat stat-cyan"><span>Total Stok</span><strong>{{ $summary['units'] }}</strong><small>unit tersedia</small></div></div><div class="col-6 col-lg-3"><div class="sparepart-stat stat-orange"><span>Stok Menipis</span><strong>{{ $summary['low_stock'] }}</strong><small>perlu diperiksa</small></div></div><div class="col-6 col-lg-3"><div class="sparepart-stat stat-green"><span>Transaksi</span><strong>{{ $summary['transactions'] }}</strong><small>catatan tersimpan</small></div></div></div>
    <div class="row g-4 mb-4">
        <div class="col-xl-5"><section class="card sparepart-panel h-100"><div class="card-header"><span class="panel-kicker">MASTER DATA</span><h2>{{ $editing ? 'Edit Jenis Sparepart' : 'Tambah Jenis Sparepart' }}</h2><p>Catat komponen yang digunakan untuk perbaikan dan pemeliharaan IT.</p></div><div class="card-body"><form method="POST" action="{{ $editing ? route('spareparts.types.update', $editing) : route('spareparts.types.store') }}" class="row g-3">@csrf @if($editing) @method('PUT') @endif
            <div class="col-md-5"><label class="form-label">Kode Sparepart</label><input class="form-control" value="{{ $editing?->code ?? 'Otomatis saat disimpan' }}" readonly><div class="form-text">Format: SP-0001</div></div><div class="col-md-7"><label class="form-label">Nama Sparepart</label><input name="name" class="form-control" value="{{ old('name', $editing?->name) }}" placeholder="RAM DDR4 8GB" required></div>
            <div class="col-md-6"><label class="form-label">Kategori</label><input name="category" class="form-control" value="{{ old('category', $editing?->category) }}" placeholder="Komponen / Kabel / Aksesori"></div><div class="col-md-6"><label class="form-label">Merek</label><input name="brand" class="form-control" value="{{ old('brand', $editing?->brand) }}" placeholder="Kingston, Logitech"></div>
            <div class="col-md-6"><label class="form-label">Satuan</label><input name="unit" class="form-control" value="{{ old('unit', $editing?->unit ?: 'pcs') }}" required></div><div class="col-md-6"><label class="form-label">Batas Minimum</label><input type="number" name="minimum_stock" class="form-control" min="0" value="{{ old('minimum_stock', $editing?->minimum_stock ?? 0) }}" required></div>
            <div class="col-12"><label class="form-label">Catatan</label><textarea name="notes" class="form-control" rows="2">{{ old('notes', $editing?->notes) }}</textarea></div><div class="col-12 d-flex gap-2"><button class="btn btn-brand">{{ $editing ? 'Simpan Perubahan' : 'Tambah Master' }}</button>@if($editing)<a href="{{ route('spareparts.index') }}" class="btn btn-outline-secondary">Batal</a>@endif</div>
        </form></div></section></div>
        <div class="col-xl-7"><section class="card sparepart-panel h-100"><div class="card-header"><span class="panel-kicker">PERGERAKAN STOK</span><h2>Catat Transaksi</h2><p>Gunakan <strong>Stok Masuk</strong> untuk pengadaan dan <strong>Stok Keluar</strong> untuk pemakaian.</p></div><div class="card-body"><form method="POST" action="{{ route('spareparts.transactions.store') }}" class="row g-3">@csrf
            <div class="col-md-6"><label class="form-label">Jenis Sparepart</label><select name="sparepart_type_id" class="form-select" required><option value="">-- Pilih Sparepart --</option>@foreach($sparepartTypes as $part)<option value="{{ $part->id }}">{{ $part->code }} - {{ $part->name }} | Stok: {{ $part->current_stock }} {{ $part->unit }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Peralatan Tujuan</label><select name="equipment_id" class="form-select"><option value="">-- Pilih Peralatan --</option>@foreach($equipmentOptions as $equipment)<option value="{{ $equipment->id }}">{{ $equipment->name }} - {{ $equipment->owner_name ?: ($equipment->owner->name ?? 'PIC belum diisi') }} - {{ $equipment->assetLocation->name ?? $equipment->getRawOriginal('location') ?: 'Lokasi belum diisi' }}</option>@endforeach</select><div class="form-text">Format: Nama Peralatan - PIC - Lokasi.</div></div><div class="col-md-5"><label class="form-label">Jenis Transaksi</label><select name="type" class="form-select" required><option value="in">Stok Masuk</option><option value="out">Stok Keluar</option></select></div>
            <div class="col-md-4"><label class="form-label">Jumlah</label><input type="number" name="quantity" class="form-control" min="1" required></div><div class="col-md-8"><label class="form-label">Tanggal</label><input type="date" name="transaction_date" class="form-control" value="{{ date('Y-m-d') }}" required></div>
            <div class="col-md-6"><label class="form-label">Nomor Referensi</label><input name="reference" class="form-control" placeholder="Nota / PO / dokumen"></div><div class="col-md-6"><label class="form-label">Pemakai / Penerima</label><input name="recipient" class="form-control" placeholder="Nama user atau bagian"></div><div class="col-12"><label class="form-label">Keterangan</label><textarea name="notes" class="form-control" rows="2" placeholder="Keterangan pengadaan atau pemakaian"></textarea></div><div class="col-12"><button class="btn btn-sparepart">Simpan Transaksi</button></div>
        </form></div></section></div>
    </div>
    <section class="card sparepart-panel mb-4"><div class="card-header d-flex justify-content-between align-items-center gap-3"><div><span class="panel-kicker">MASTER JENIS SPAREPART</span><h2 class="mb-0">Daftar Stok</h2></div><form method="GET" action="{{ route('spareparts.index') }}" class="sparepart-search"><input name="search" value="{{ $search }}" class="form-control form-control-sm" placeholder="Cari sparepart..."><button class="btn btn-sm btn-outline-primary">Cari</button></form></div><div class="table-responsive"><table class="table sparepart-table align-middle mb-0"><thead><tr><th>Kode / Nama</th><th>Kategori</th><th>Merek</th><th>Stok</th><th>Minimum</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($sparepartTypes as $part)<tr><td><strong>{{ $part->code }}</strong><span class="d-block">{{ $part->name }}</span><small class="text-muted">{{ $part->transactions_count }} transaksi</small></td><td>{{ $part->category ?: '-' }}</td><td>{{ $part->brand ?: '-' }}</td><td><strong class="stock-number">{{ $part->current_stock }}</strong> {{ $part->unit }}</td><td>{{ $part->minimum_stock }} {{ $part->unit }}</td><td>@if($part->is_low_stock)<span class="part-badge part-low">Stok Menipis</span>@else<span class="part-badge part-ready">Aman</span>@endif</td><td class="text-nowrap"><a href="{{ route('spareparts.index', ['edit' => $part->id]) }}" class="btn btn-sm btn-outline-primary">Edit</a><form method="POST" action="{{ route('spareparts.types.destroy', $part) }}" class="d-inline" onsubmit="return confirm('Hapus jenis sparepart ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada jenis sparepart.</td></tr>@endforelse</tbody></table></div><div class="table-pagination">{{ $sparepartTypes->links() }}</div></section>
    <section class="card sparepart-panel"><div class="card-header"><span class="panel-kicker">AUDIT STOK</span><h2>Riwayat Stok Masuk &amp; Keluar</h2><p class="mb-0">Saldo sebelum dan sesudah transaksi tersimpan untuk setiap perubahan.</p></div><div class="table-responsive"><table class="table sparepart-table align-middle mb-0"><thead><tr><th>Tanggal</th><th>Sparepart</th><th>Peralatan Tujuan</th><th>Transaksi</th><th>Jumlah</th><th>Saldo</th><th>Referensi / Keterangan</th><th>Petugas</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr><td>{{ $transaction->transaction_date?->format('d M Y') }}</td><td><strong>{{ $transaction->sparepartType->code }}</strong><small class="d-block">{{ $transaction->sparepartType->name }}</small></td><td>@if($transaction->equipment)<strong>{{ $transaction->equipment->name }}</strong><small class="d-block text-muted">{{ $transaction->equipment->owner_name ?: ($transaction->equipment->owner->name ?? 'PIC belum diisi') }} - {{ $transaction->equipment->assetLocation->name ?? $transaction->equipment->getRawOriginal('location') ?: 'Lokasi belum diisi' }}</small>@else Tidak dikaitkan @endif</td><td>@if($transaction->type === 'in')<span class="part-badge part-in">+ Stok Masuk</span>@else<span class="part-badge part-out">- Stok Keluar</span>@endif</td><td><strong>{{ $transaction->quantity }}</strong> {{ $transaction->sparepartType->unit }}</td><td>{{ $transaction->stock_before }} &rarr; <strong>{{ $transaction->stock_after }}</strong></td><td>{{ $transaction->reference ?: '-' }}@if($transaction->recipient)<small class="d-block text-muted">Penerima: {{ $transaction->recipient }}</small>@endif @if($transaction->notes)<small class="d-block text-muted">{{ $transaction->notes }}</small>@endif</td><td>{{ $transaction->creator->name ?? '-' }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Belum ada transaksi stok.</td></tr>@endforelse</tbody></table></div><div class="table-pagination">{{ $transactions->links('pagination::bootstrap-5') }}</div></section>
</div>
<style>
.sparepart-page{color:#17324d}.sparepart-hero{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:28px 32px;border-radius:10px;background:linear-gradient(120deg,#334155,#0f766e);color:#fff}.sparepart-eyebrow,.panel-kicker{font-size:.7rem;font-weight:800;letter-spacing:.13em}.sparepart-hero h1{margin:5px 0;font-size:2rem}.sparepart-hero p{margin:0;max-width:560px;color:#dbeafe}.sparepart-hero-mark{min-width:155px;padding:18px;border:1px solid rgba(255,255,255,.35);border-radius:8px;text-align:center;font-size:1.5rem;font-weight:800;letter-spacing:.08em}.sparepart-hero-mark span{font-size:.58rem;letter-spacing:.12em}.sparepart-stat{padding:16px 18px;border:1px solid #dbe5ef;border-top:4px solid #334155;background:#fff}.sparepart-stat span,.sparepart-stat small{display:block;color:#64748b;font-size:.76rem}.sparepart-stat strong{display:block;margin:2px 0;font-size:1.65rem}.stat-cyan{border-top-color:#0891b2}.stat-orange{border-top-color:#f59e0b}.stat-green{border-top-color:#16a34a}.sparepart-panel{border:1px solid #dbe5ef;box-shadow:0 4px 14px rgba(23,50,77,.04)}.sparepart-panel .card-header{padding:17px 20px;background:#f8fbfe;border-bottom:1px solid #e5edf4}.sparepart-panel .card-header h2{margin:4px 0 3px;font-size:1.08rem;color:#334155}.sparepart-panel .card-header p{margin:0;color:#64748b;font-size:.84rem}.panel-kicker{color:#0f766e}.sparepart-panel .card-body{padding:20px}.sparepart-panel .form-label{margin-bottom:4px;color:#475569;font-size:.78rem;font-weight:700}.btn-sparepart{background:#0f766e;color:#fff;font-weight:700}.btn-sparepart:hover{background:#115e59;color:#fff}.sparepart-search{display:flex;gap:7px;width:280px}.sparepart-table{font-size:.86rem}.sparepart-table thead th{background:#f1f5f9;color:#475569;font-size:.76rem;text-transform:uppercase;letter-spacing:.03em}.stock-number{color:#0f766e;font-size:1.05rem}.part-badge{display:inline-block;padding:4px 7px;border-radius:4px;font-size:.7rem;font-weight:800}.part-low,.part-out{background:#fee2e2;color:#991b1b}.part-ready,.part-in{background:#dcfce7;color:#166534}@media(max-width:700px){.sparepart-hero{padding:22px;align-items:flex-start}.sparepart-hero-mark{display:none}.sparepart-search{width:100%}.sparepart-panel .card-header{align-items:flex-start!important;flex-direction:column}}
</style>
@endsection
