@extends('layouts.app')

@section('content')
<div class="container mt-4 profile-page">
    <div class="profile-hero mb-4"><div><div class="profile-kicker">PENGATURAN AKUN</div><h1>Profil Saya</h1><p>Kelola foto profil dan keamanan password akun Anda.</p></div><div class="profile-identity"><img src="{{ $user->profile_photo_path ? asset('storage/' . $user->profile_photo_path) : asset('images/default-avatar.svg') }}" alt="Foto profil {{ $user->name }}"></div></div>
    @if ($errors->any())<div class="alert alert-danger"><ul class="mb-0 ps-3">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row g-4"><div class="col-lg-5"><section class="card profile-card h-100"><div class="card-body"><h2>Foto Profil</h2><p class="text-muted">Foto ini digunakan sebagai identitas visual akun Anda.</p><div class="profile-photo-preview"><img src="{{ $user->profile_photo_path ? asset('storage/' . $user->profile_photo_path) : asset('images/default-avatar.svg') }}" alt="Foto profil {{ $user->name }}"></div><form method="POST" action="{{ route('profile.photo.update') }}" enctype="multipart/form-data" class="mt-3">@csrf<label class="form-label">Pilih Foto Baru</label><input type="file" name="profile_photo" class="form-control @error('profile_photo') is-invalid @enderror" accept=".jpg,.jpeg,.png,.webp" required><small class="text-muted">JPG, PNG, atau WebP. Maksimum 2 MB.</small><button class="btn btn-primary mt-3">Simpan Foto</button></form>@if($user->profile_photo_path)<form method="POST" action="{{ route('profile.photo.destroy') }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-link text-danger mt-3">Hapus Foto</button></form>@endif</div></section></div><div class="col-lg-7"><section class="card profile-card h-100"><div class="card-body"><h2>Ganti Password</h2><p class="text-muted">Gunakan password baru minimal 8 karakter dan jangan bagikan kepada orang lain.</p><form method="POST" action="{{ route('profile.password.update') }}" class="row g-3">@csrf @method('PUT')<div class="col-12"><label class="form-label">Password Saat Ini</label><input type="password" name="current_password" class="form-control @error('current_password') is-invalid @enderror" required autocomplete="current-password"></div><div class="col-md-6"><label class="form-label">Password Baru</label><input type="password" name="password" class="form-control @error('password') is-invalid @enderror" required autocomplete="new-password"></div><div class="col-md-6"><label class="form-label">Konfirmasi Password Baru</label><input type="password" name="password_confirmation" class="form-control" required autocomplete="new-password"></div><div class="col-12"><button class="btn btn-primary">Ubah Password</button></div></form></div></section></div></div>
    <section class="card profile-card mt-4"><div class="card-body"><h2>Informasi Akun</h2><dl class="row mb-0"><dt class="col-md-3">Nama</dt><dd class="col-md-9">{{ $user->name }}</dd><dt class="col-md-3">Email</dt><dd class="col-md-9">{{ $user->email }}</dd><dt class="col-md-3">Departemen</dt><dd class="col-md-9">{{ $user->department ?: '-' }}</dd><dt class="col-md-3">Hak Akses</dt><dd class="col-md-9">{{ $user->roleLabel() }}</dd></dl></div></section>
</div>
<style>.profile-page{color:#17324d}.profile-hero{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:27px 30px;background:linear-gradient(120deg,#075985,#0f766e);color:#fff;border-radius:8px}.profile-kicker{font-size:.7rem;font-weight:800;letter-spacing:.12em}.profile-hero h1{margin:5px 0;font-size:2rem}.profile-hero p{margin:0;color:#dbeafe}.profile-identity,.profile-photo-preview{display:flex;align-items:center;justify-content:center;overflow:hidden;border-radius:50%;background:#e0f2fe;color:#075985;font-weight:800}.profile-identity{width:78px;height:78px;border:3px solid rgba(255,255,255,.5);font-size:1.8rem}.profile-identity img,.profile-photo-preview img{width:100%;height:100%;object-fit:cover}.profile-card{border:1px solid #dbe5ef}.profile-card h2{font-size:1.1rem;color:#075985}.profile-photo-preview{width:128px;height:128px;margin:18px auto;font-size:3rem;border:3px solid #cbd5e1}@media(max-width:576px){.profile-hero{padding:22px;align-items:flex-start}.profile-identity{width:62px;height:62px}}</style>
@endsection
