<?php

return [
    ['text' => 'Teknologi terbaik adalah teknologi yang membuat manusia bekerja lebih cerdas, bukan lebih keras.', 'author' => 'Satya Nadella'],
    ['text' => 'Inovasi membedakan antara seorang pemimpin dan seorang pengikut.', 'author' => 'Steve Jobs'],
    ['text' => 'Kesuksesan bukan tentang seberapa cepat kita sampai, tetapi seberapa konsisten kita terus melangkah.', 'author' => 'Consistency Principle'],
    ['text' => 'Jangan takut berjalan perlahan, takutlah jika berhenti melangkah.', 'author' => 'Growth Mindset'],
    ['text' => 'Perubahan kecil yang dilakukan secara konsisten dapat menghasilkan perubahan besar.', 'author' => 'Continuous Growth'],
    ['text' => 'Kesempatan sering kali datang kepada mereka yang telah mempersiapkan diri.', 'author' => 'Preparation Principle'],
    ['text' => 'Disiplin adalah melakukan apa yang harus dilakukan, bahkan ketika tidak ingin melakukannya.', 'author' => 'Discipline Principle'],
    ['text' => 'Kegagalan bukan akhir dari perjalanan, melainkan bagian dari proses untuk menjadi lebih baik.', 'author' => 'Growth Principle'],
    ['text' => 'Orang hebat bukan mereka yang tidak pernah gagal, tetapi mereka yang selalu belajar dari kegagalan.', 'author' => 'Learning Principle'],
    ['text' => 'Masa depan dibangun dari keputusan dan tindakan yang kita lakukan hari ini.', 'author' => 'Future Mindset'],
    ['text' => 'Jadilah lebih baik dari dirimu yang kemarin, bukan lebih baik dari orang lain.', 'author' => 'Personal Growth'],
    ['text' => 'Tidak ada hasil besar tanpa proses yang dijalani dengan kesabaran dan ketekunan.', 'author' => 'Persistence Principle'],
    ['text' => 'Kesempatan tidak selalu datang dua kali, tetapi persiapan yang baik membuat kita siap ketika kesempatan datang.', 'author' => 'Opportunity Principle'],
    ['text' => 'Kerja sama yang kuat mampu mengubah tantangan besar menjadi pencapaian bersama.', 'author' => 'Collaboration Principle'],
    ['text' => 'Pemimpin yang baik tidak hanya menunjukkan arah, tetapi juga membantu orang lain berkembang.', 'author' => 'Leadership Principle'],
    ['text' => 'Kejujuran mungkin tidak selalu menjadi jalan termudah, tetapi selalu menjadi dasar yang kuat.', 'author' => 'Integrity Principle'],
    ['text' => 'Apa yang kita lakukan setiap hari menentukan siapa kita di masa depan.', 'author' => 'Daily Progress'],
    ['text' => 'Jangan menunggu keadaan sempurna untuk memulai sesuatu yang baik.', 'author' => 'Action Principle'],
    ['text' => 'Belajar adalah investasi yang tidak pernah kehilangan nilainya.', 'author' => 'Learning Mindset'],
    ['text' => 'Kesabaran membuat kita mampu melihat peluang yang sering terlewatkan oleh ketergesaan.', 'author' => 'Patience Principle'],
    ['text' => 'Ketika kita bekerja dengan tujuan yang jelas, setiap langkah memiliki arti.', 'author' => 'Purpose Principle'],
    ['text' => 'Tantangan tidak selalu datang untuk menghentikan kita, terkadang ia datang untuk menunjukkan kemampuan kita.', 'author' => 'Resilience Principle'],
    ['text' => 'Kualitas lahir dari kepedulian terhadap hal-hal kecil.', 'author' => 'Quality Mindset'],
    ['text' => 'Berani memulai adalah langkah pertama menuju sesuatu yang lebih besar.', 'author' => 'Courage Principle'],
    ['text' => 'Kesuksesan sejati adalah ketika pencapaian kita juga membawa manfaat bagi orang lain.', 'author' => 'Success Principle'],
    ['text' => 'Waktu adalah sumber daya yang paling berharga karena tidak dapat dikembalikan.', 'author' => 'Time Principle'],
    ['text' => 'Pikiran yang terbuka membuat kita mampu melihat peluang di tengah perubahan.', 'author' => 'Open Mindset'],
    ['text' => 'Tidak semua hal dapat kita kendalikan, tetapi kita selalu dapat mengendalikan bagaimana kita meresponsnya.', 'author' => 'Resilience Mindset'],
    ['text' => 'Satu langkah kecil hari ini lebih berarti daripada seribu rencana yang tidak pernah dimulai.', 'author' => 'Action Mindset'],
    ['text' => 'Jangan hanya mencari hasil yang baik, bangunlah proses yang menghasilkan kebaikan secara konsisten.', 'author' => 'Process Principle'],
    ['text' => 'Kebaikan yang dilakukan dengan tulus mungkin sederhana, tetapi dampaknya dapat bertahan lama.', 'author' => 'Humanity Principle'],
    ['text' => 'Ketika tujuan besar terasa jauh, fokuslah menyelesaikan satu langkah dengan sebaik mungkin.', 'author' => 'Focus Principle'],
    ['text' => 'Perubahan adalah satu-satunya konstan dalam dunia teknologi.', 'author' => 'Heraclitus'],
    ['text' => 'Sistem yang tangguh dibuat bukan dari ketiadaan masalah, melainkan dari ketanggapan dalam menyelesaikannya.', 'author' => 'IT Excellence Principle'],
    ['text' => 'Keamanan dan stabilitas infrastruktur adalah fondasi dari setiap kemajuan digital.', 'author' => 'Operational Wisdom'],
    ['text' => 'Detail kecil dalam pemeliharaan hari ini mencegah gangguan besar di masa depan.', 'author' => 'Preventive Care Standard'],
    ['text' => 'Kerja keras mengalahkan bakat ketika bakat tidak bekerja keras.', 'author' => 'Tim Notke'],
    ['text' => 'Kesederhanaan adalah kunci utama dari keandalan perangkat lunak dan sistem.', 'author' => 'Edsger W. Dijkstra'],
    ['text' => 'Kualitas bukanlah sebuah tindakan, melainkan sebuah kebiasaan.', 'author' => 'Aristoteles'],
    ['text' => 'Setiap masalah dalam IT adalah peluang untuk menciptakan solusi yang lebih baik.', 'author' => 'Continuous Improvement'],
    ['text' => 'Fokus pada solusi, tingkatkan otomatisasi, dan jaga integritas data.', 'author' => 'IT Mindset'],
    ['text' => 'Fokus pada proses yang benar, maka hasil yang luar biasa akan mengikuti.', 'author' => 'Operational Motto'],
    ['text' => 'Kolaborasi yang baik dan komunikasi yang jernih adalah kunci sukses tim IT.', 'author' => 'Teamwork Principle'],
];
