@extends('layouts.app')

@section('content')
<div class="container mt-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><div class="web-check-eyebrow">Web Operations</div><h2 class="mb-1">Form Checklist Web Monitoring</h2><p class="text-muted mb-0">Pilih fungsi Keamanan atau Fungsional Web untuk menampilkan item yang relevan.</p></div><a href="{{ route('web-monitoring-checklists.index') }}" class="btn btn-outline-secondary">Kembali</a></div>@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<form method="POST" action="{{ route('web-monitoring-checklists.store') }}">@csrf<div class="card web-check-card"><div class="card-header">CHECKLIST OPERASIONAL WEB MONITORING</div><div class="card-body"><div class="row g-3 mb-3"><div class="col-md-4"><label class="form-label">Fungsi Checklist</label><select id="checklistType" name="checklist_type" class="form-select" required><option value="functional" {{ old('checklist_type', 'functional') === 'functional' ? 'selected' : '' }}>Fungsional Web</option><option value="security" {{ old('checklist_type') === 'security' ? 'selected' : '' }}>Keamanan Web</option></select></div><div class="col-md-4"><label class="form-label">Situs / Layanan</label><select name="site_id" class="form-select" required><option value="">-- Pilih Situs --</option>@foreach($sites as $site)<option value="{{ $site->id }}" {{ old('site_id') == $site->id ? 'selected' : '' }}>{{ $site->name }} - {{ $site->url }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Tanggal & Jam</label><input type="datetime-local" name="checked_at" class="form-control" value="{{ old('checked_at', now()->format('Y-m-d\TH:i')) }}" required></div><div class="col-md-2"><label class="form-label">Pemeriksa</label><input name="checked_by" class="form-control" value="{{ old('checked_by') }}"></div></div><div class="checklist-type-note" id="checklistTypeNote"></div><div class="table-responsive"><table class="table table-bordered web-check-table"><thead><tr><th>No.</th><th>Area Pemeriksaan</th><th class="text-center">Sesuai</th><th class="text-center">Tidak Sesuai</th><th class="text-center">N/A</th><th>Keterangan / Tindak Lanjut</th></tr></thead><tbody id="checklistItemsBody"></tbody></table></div><div class="mt-3"><label class="form-label">Catatan Umum</label><textarea name="notes" class="form-control" rows="2">{{ old('notes') }}</textarea></div></div><div class="card-footer text-end"><button class="btn btn-brand">Simpan Checklist</button></div></div></form></div>
<script>
const checklistItems = @json($itemsByType);
const checklistType = document.getElementById('checklistType');
const checklistItemsBody = document.getElementById('checklistItemsBody');
const checklistTypeNote = document.getElementById('checklistTypeNote');
function renderChecklistItems() {
	const type = checklistType.value;
	const items = checklistItems[type] || [];
	checklistTypeNote.textContent = type === 'security' ? 'Checklist Keamanan Web: kontrol SSL, akses, patch, backup, audit log, dan perlindungan informasi.' : 'Checklist Fungsional Web: availability, performa, halaman, login, transaksi, data, laporan, dan notifikasi.';
	checklistItemsBody.innerHTML = items.map((item, index) => `<tr><td>${index + 1}</td><td>${item.name}<input type="hidden" name="entries[${index}][item_code]" value="${item.code}"><input type="hidden" name="entries[${index}][item_name]" value="${item.name}"></td><td class="text-center"><input type="radio" name="entries[${index}][result]" value="pass" checked></td><td class="text-center"><input type="radio" name="entries[${index}][result]" value="fail"></td><td class="text-center"><input type="radio" name="entries[${index}][result]" value="na"></td><td><input name="entries[${index}][remarks]" class="form-control form-control-sm" placeholder="Keterangan bila ada temuan"></td></tr>`).join('');
}
checklistType.addEventListener('change', renderChecklistItems); renderChecklistItems();
</script>
<style>.web-check-eyebrow{color:#0b5ea8;font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.web-check-card{border:1px solid #dbe5ef}.web-check-card .card-header{background:#fff6e4;color:#17324d;font-weight:700}.web-check-table th{background:#f8fafc;font-size:.8rem}.web-check-table td{vertical-align:middle}.checklist-type-note{margin-bottom:12px;padding:10px 12px;background:#edf5fc;border-left:3px solid #0b5ea8;color:#36546f;font-size:.82rem}</style>
@endsection
