@extends('layouts.app')

@section('content')
<div class="container mt-4 asset-page">
    <div class="d-flex justify-content-between align-items-start mb-3"><div><div class="asset-eyebrow">IT Asset Management</div><h2 class="mb-1">Peralatan IT</h2><p class="text-muted mb-0">Inventaris aset, kondisi, lokasi, dan informasi teknis peralatan IT.</p></div><a href="{{ route('equipments.create') }}" class="btn btn-brand">Tambah Peralatan</a></div>
    <div class="row g-3 mb-3"><div class="col-md-4"><div class="asset-stat total"><span>Total Aset</span><strong>{{ $summary['total'] }}</strong><small>aset terdaftar</small></div></div><div class="col-md-4"><div class="asset-stat active"><span>Kondisi Normal</span><strong>{{ $summary['active'] }}</strong><small>siap digunakan</small></div></div><div class="col-md-4"><div class="asset-stat attention"><span>Perlu Perhatian</span><strong>{{ $summary['attention'] }}</strong><small>rusak atau perbaikan</small></div></div></div>
    <div class="card asset-list"><div class="card-header"><strong>Daftar Peralatan</strong></div><div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Peralatan</th><th>Tipe / Merk</th><th>Lokasi</th><th>Identitas</th><th>Kondisi</th><th>IP Address</th><th>Aksi</th></tr></thead><tbody>@forelse($equipments as $eq)@php $condition = $eq->condition ?? $eq->status ?? 'tidak dicatat'; $conditionClass = in_array($condition, ['rusak','perbaikan']) ? 'condition-attention' : 'condition-good'; @endphp<tr><td><div class="asset-cell">@if($eq->photo_path)<img src="{{ asset('storage/' . $eq->photo_path) }}" alt="{{ $eq->name }}">@else<span class="asset-initial">IT</span>@endif<div><strong>{{ $eq->name }}</strong><small>{{ $eq->asset_tag ?? $eq->serial_number ?? '-' }}</small></div></div></td><td><strong>{{ $eq->type->name ?? '-' }}</strong><small>{{ $eq->manufacturer->name ?? $eq->model ?? '-' }}</small></td><td>{{ $eq->assetLocation?->name ?: $eq->getRawOriginal('location') ?: '-' }}</td><td><span>{{ $eq->serial_number ?? '-' }}</span><small>{{ $eq->capacity ?? '-' }}</small></td><td><span class="condition-badge {{ $conditionClass }}">{{ ucfirst($condition) }}</span></td><td>{{ $eq->ip_address ?? '-' }}</td><td class="text-nowrap"><a href="{{ route('equipments.show', $eq) }}" class="btn btn-sm btn-outline-secondary">Detail</a><a href="{{ route('equipments.edit', $eq) }}" class="btn btn-sm btn-outline-primary">Edit</a><form action="{{ route('equipments.destroy', $eq) }}" method="POST" class="d-inline" onsubmit="return confirm('Hapus peralatan ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada peralatan IT.</td></tr>@endforelse</tbody></table></div><div class="table-pagination">{{ $equipments->links() }}</div></div></div>
</div>
<style>.asset-eyebrow{color:#0b5ea8;font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.asset-stat{padding:15px 17px;background:#fff;border:1px solid #dbe5ef;border-top:4px solid #64748b}.asset-stat span,.asset-stat small{display:block;color:#64748b;font-size:.76rem}.asset-stat strong{display:block;font-size:1.65rem}.asset-stat.total{border-top-color:#0b5ea8}.asset-stat.active{border-top-color:#159957}.asset-stat.attention{border-top-color:#f59e0b}.asset-list{border:1px solid #dbe5ef}.asset-list .card-header{background:#f8fafc}.asset-list small{display:block;color:#64748b}.asset-cell{display:flex;align-items:center;gap:10px}.asset-cell img,.asset-initial{width:38px;height:38px;flex:0 0 38px;object-fit:cover;border-radius:5px;border:1px solid #dbe5ef}.asset-initial{display:flex;align-items:center;justify-content:center;background:#edf5fc;color:#0b5ea8;font-size:.7rem;font-weight:700}.condition-badge{display:inline-block;padding:4px 7px;border-radius:3px;font-size:.74rem;font-weight:700}.condition-good{background:#dcfce7;color:#166534}.condition-attention{background:#fee2e2;color:#991b1b}</style>
@endsection
