@extends('layouts.app')

@section('content')
<div class="container mt-4 iso-library">
    <div class="iso-hero mb-4"><div><div class="iso-kicker">ISO DOCUMENT CONTROL</div><h1>Ruang Dokumen ISO</h1><p>Folder dokumen terkendali yang dibagikan hanya kepada penerima yang ditetapkan.</p></div>@if(auth()->user()->isMaster() || auth()->user()->isAdminIt())<a href="{{ route('iso-documents.create') }}" class="btn btn-light">Buat Folder</a>@endif</div>
    <div class="row g-3 mb-4"><div class="col-md-4"><div class="iso-stat"><span>Dokumen Tersedia</span><strong>{{ $summary['available'] }}</strong><small>sesuai akses Anda</small></div></div><div class="col-md-4"><div class="iso-stat iso-stat-teal"><span>Kategori Dokumen</span><strong>{{ $summary['categories'] }}</strong><small>klasifikasi tersedia</small></div></div><div class="col-md-4"><div class="iso-stat iso-stat-gold"><span>Dibagikan Kepada Saya</span><strong>{{ $summary['shared_with_me'] }}</strong><small>dokumen yang Anda terima</small></div></div></div>
    <section class="card iso-panel"><div class="card-header d-flex flex-wrap align-items-center justify-content-between gap-2"><div><div class="iso-kicker">DOCUMENT LIBRARY</div><h2>Dokumen Tersedia</h2></div><form method="GET" class="iso-search"><input name="search" value="{{ $search }}" class="form-control" placeholder="Cari nomor, judul, kategori"><button class="btn btn-outline-primary">Cari</button></form></div><div class="card-body"><div class="row g-3">@forelse ($documents as $document)<div class="col-md-6 col-xl-4"><article class="iso-document"><div class="iso-document-top"><span>{{ $document->document_number }}</span><span>{{ $document->revision ? 'Rev. ' . $document->revision : 'Tanpa Revisi' }}</span></div><h3>{{ $document->title }}</h3><p>{{ \Illuminate\Support\Str::limit($document->description, 120) ?: 'Tidak ada deskripsi dokumen.' }}</p><div class="iso-document-meta"><span>{{ $document->category }}</span><span>{{ $document->document_date?->format('d M Y') ?? '-' }}</span></div><div class="iso-document-footer"><small>Oleh {{ $document->creator->name ?? '-' }}</small><span class="iso-file-count"><i class="bi bi-folder2-open"></i> {{ $document->files_count }} file</span><a href="{{ route('iso-documents.show', $document) }}" class="btn btn-sm btn-outline-primary">Buka</a></div></article></div>@empty<div class="col-12 text-center text-muted py-5">Tidak ada dokumen yang dapat diakses.</div>@endforelse</div></div></section>
    <div class="table-pagination">{{ $documents->links() }}</div>
</div>
<style>.iso-library{color:#18324a}.iso-hero{display:flex;justify-content:space-between;align-items:center;gap:24px;padding:28px 32px;background:linear-gradient(120deg,#075985,#0f766e);color:#fff;border-radius:8px}.iso-kicker{font-size:.7rem;font-weight:800;letter-spacing:.12em}.iso-hero h1{margin:5px 0;font-size:2rem}.iso-hero p{max-width:620px;margin:0;color:#dbeafe}.iso-stat{padding:16px 18px;background:#fff;border:1px solid #dbe5ef;border-top:4px solid #075985}.iso-stat span,.iso-stat small{display:block;color:#64748b;font-size:.78rem}.iso-stat strong{display:block;font-size:1.65rem}.iso-stat-teal{border-top-color:#0f766e}.iso-stat-gold{border-top-color:#ca8a04}.iso-panel{border:1px solid #dbe5ef}.iso-panel .card-header{padding:18px 20px;background:#f8fafc}.iso-panel h2{margin:4px 0 0;font-size:1.1rem}.iso-search{display:flex;gap:8px;width:min(100%,340px)}.iso-document{height:100%;padding:16px;border:1px solid #dbe5ef;border-radius:6px;background:#fff}.iso-document-top,.iso-document-meta,.iso-document-footer{display:flex;justify-content:space-between;gap:8px}.iso-document-top{font-size:.7rem;color:#0369a1;font-weight:800}.iso-document-top span:last-child{color:#64748b}.iso-document h3{margin:14px 0 7px;font-size:1rem}.iso-document p{min-height:42px;margin:0;color:#64748b;font-size:.84rem}.iso-document-meta{padding-top:12px;font-size:.75rem;font-weight:700}.iso-document-footer{align-items:center;padding-top:14px;margin-top:12px;border-top:1px solid #e2e8f0}.iso-file-count{margin-right:auto;color:#0f766e;font-size:.72rem;font-weight:700}.iso-file-count i{margin-right:4px}@media(max-width:576px){.iso-hero{padding:22px;align-items:flex-start;flex-direction:column}.iso-search{width:100%}}</style>
@endsection
